### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by abh** [eclipse/paho.golang#110]
The rare releases (and low version numbers) make it seem like this is still an experimental / "maybe in the future" project, but using the "legacy" library for a few days I realized that can't possibly be. :-)

So... would it make sense to tag a new version so "go get" will by default use newer code?

**Comment by jerrdasur** [comment]
+1
Also need a new release, because v0.10.0 don't have a support for shared subscriptions. Need a fix for router from master branch.

**Comment by MattBrittan** [comment]
I have made a new release. Had been awaiting @alsm, but have been unable to make contact, and as it's been quite a while since the last release I felt it was time!
Note that I have not moved up to V1; the main reason for this is the missing support for full QOS 1/2 (the library currently NEVER resends a message). Implementing this may require changes to the API so I feel we should hold off on V1 until that has been implemented (and keeping this below v1 indicates that its not yet feature complete).

**Comment by seinshah** [comment]
Hi,
Sorry for reopening this. Is there any plan to tag changes regularly?
I noticed that there a lot of fixes since v0.11 and rather importing the latest version by tags instead of master's HEAD.
I attempted to create issues and PRs for several issues which noticed that are already fixed on master branch, but are not tagged yet.

**Comment by MattBrittan** [comment]
>Sorry for reactivating this. Is there any plan to tag changes regularly?

You didn't (the issue is still closed :-) ).

We are currently working on a major change (full QOS1/2 support) so would aim to make a release before that's added to master (as it will be a large change). I would expect this to happen later in the month. 
Generally a release has been made when a major fix has been introduced but this has been somewhat sporadic. I think part of this has been because the main committers (ALSM and myself) have not actually been using the library -  this will change once the big PR hits (I'm still using the v3 client because I need the library to handle persistence and queueing messages whilst the connection is unavailable; the upcoming change addresses both points).

**Comment by seinshah** [comment]
Thanks @MattBrittan. (By activating I mostly meant drawing your attention to the issue again :))
That makes sense and hope everything goes as planned.
I mentioned this as I was facing a race condition in autopaho after adding a custom Logger and when attempted to create an issue for it and a PR, realized that it is already fixed in master.
🤞
